### ISSUE TITLE
因配置错误导致的的 SignatureDoesNotMatch

### ISSUE THREAD

**Issue by ColdZoo** [h46incon/AliDDNSBash#10]
main函数中， 若每次只执行describe/update中的一种， 没有问题。 但若将main函数改为 如下形式， 将会报 

> SignatureDoesNotMatch

错误
```
main()                
{                                     
        describe_record                     
        update_record             
}

```

**Comment by ColdZoo** [comment]
经过比较，

>  String to Signed 
内的内容， 可以发现， 同时执行两个函数的时候， 会出现accessKeyId 等参数被拼接了两遍。 若能在shell中增加一些初始化, 会比较好？

**Comment by 605435218** [comment]
一个脚本里面只运行一个函数就行了，不影响使用

**Comment by ColdZoo** [comment]
ok, thank you very much
