### ISSUE TITLE
在群晖6.2.1系统中不可以更新域名

### ISSUE THREAD

**Issue by iamhaifeng** [h46incon/AliDDNSBash#11]
在群晖6.2.1系统中可以查询域名，但是在更新域名时报SignatureDoesNotMatch。

经排查，发现群晖6.2.1自带的sort命令（version: 8.24）在排序时会把RR字段排到RecordId之后（正常情况下应该是RR排在RecordId之前，第二个R字符比e字符的ASCII码要小）。

解决办法，修改 LC_COLLATE=C 为 LC_ALL=C 。

在群晖6.2.1和Ubuntu 18.04.4中通过。

**Comment by iamhaifeng** [comment]
更改标题

**Comment by h46incon** [comment]
谢谢告知，见 #12  ，已修复
