### ISSUE TITLE
OpenSSL 1.1.0版本获取随机数命令变化

### ISSUE THREAD

**Issue by debuggerx01** [h46incon/AliDDNSBash#3]
你好，我在OpenSSL1.1.0版本上运行脚本时报错，发现是脚本第27行
`rand_num=$(openssl rand 16 -hex)`
这句的返回结果为"Extra arguments given. rand: Use -help for summary."
将其修改为`rand_num=$(openssl rand -hex 16)`，也就是调换了下参数顺序后则可以继续正常运行。

**Comment by h46incon** [comment]
感谢告知，已修复
