### ISSUE TITLE
describe works, but update error as below

### ISSUE THREAD

**Issue by yinminang** [h46incon/AliDDNSBash#4]
{"Recommend":"https://error-center.aliyun.com/status/search?Keyword=SignatureDoesNotMatch&source=PopGw","Message":"Specified signature is not matched with our calculation. server string to sign is:*********

i want to fix but my skill on shell is so bad...

**Comment by h46incon** [comment]
Please check if the output log in `> String to Signed` is same as the error message. And please provide the following information:
- os
- shell version
- openssl version
