### ISSUE TITLE
没有返回 RecordId

### ISSUE THREAD

**Issue by Aifcce** [h46incon/AliDDNSBash#5]
{"PageNumber":1,"TotalCount":0,"PageSize":20,"RequestId":"8BC9DE56-CE15-435A-AB15-609D5842478B","DomainRecords":{"Record":[]}}HttpCode:200

**Comment by h46incon** [comment]
没有在阿里云上配置域名的记录？

**Comment by Aifcce** [comment]
我看网页手动配置相当于直接绑定，是静态的我就没配置。那我配置一个晚上再试下。
