### ISSUE TITLE
怎么查看是不是运行成功了。或者已经在后台运行

### ISSUE THREAD

**Issue by Aifcce** [h46incon/AliDDNSBash#6]

**Comment by h46incon** [comment]
呃，这个脚本没写得太完善。脚本最后会把调用API的结果打印出来，看返回信息就可以了。

**Comment by Aifcce** [comment]
我运行一下，程序就运行完结束了。 然后如果我的ip变了，它会自动更新吗？ 有后台进程在检查ip有没有改变吗

**Comment by h46incon** [comment]
嗯，运行完脚本就退出了，如果IP有变更的话会更新。
但是脚本不会常驻后台，需要你使用crontab设置定时任务定期执行。

**Comment by Aifcce** [comment]
> 嗯，运行完脚本就退出了，如果IP有变更的话会更新。
> 但是脚本不会常驻后台，需要你使用crontab设置定时任务定期执行。

我加了你while循环然后用 nohup 解决了。谢谢啦
