### ISSUE TITLE
斐讯k2p管改固件没有dig，可以用nslookup代替。

### ISSUE THREAD

**Issue by 605435218** [h46incon/AliDDNSBash#7]
get_domain_ip函数里面改成 
_func_ret=$(nslookup "${full_domain}" "${DNSServer}" | sed -n 5p | awk '{print $3}'  )

**Comment by h46incon** [comment]
感谢告知。
dig 需要安卓 bind-dig 。
我过两天验证下 nslookup 的用法。

**Comment by 605435218** [comment]
不同系统可能会有点不同，我这个在自己路由器上验证可以用

**Comment by h46incon** [comment]
见 #12 ，已直接通过 API 中获取现在的 IP。
